# -*- coding: utf-8 -*-
"""Gender recognition by voice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p__EmUlcnI1VRxNm8Bg0oLRodoQjnAJ7

IMPORT LIBRARIES
"""

import numpy as np
import pandas as pd

"""IMPORT DATASET"""

df=pd.read_csv("/content/voice.csv")
df

df.size

df.shape

df.head()

df.tail()

df.columns

df.isna().sum()

"""SEPARATE INPUT AND OUTPUT VALUES"""

#INPUT
x=df.iloc[:,:-1]
x

#OUTPUT
y=df.iloc[:,-1]
y

"""TRAIN TEST SPLIT"""

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

x_train

x_test

y_train

y_test

"""NORMALIZATION"""

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

scaler.fit(x_train)

x_train=scaler.transform(x_train)

x_test=scaler.transform(x_test)

"""MODEL CREATION"""

from sklearn.svm import SVC

model=SVC()

model.fit(x_train,y_train)

y_pred=model.predict(x_test)
y_pred

"""PERFORMANCE EVALUATION"""

from sklearn.metrics import confusion_matrix,accuracy_score,ConfusionMatrixDisplay,classification_report

report=classification_report(y_pred,y_test)
report

label=['male','female']

mat=confusion_matrix(y_pred,y_test)
cmd=ConfusionMatrixDisplay(mat,display_labels=label)
cmd.plot()

score=accuracy_score(y_pred,y_test)
score